# +=====================+
# | Module make utility |
# +=====================+

# Module information
MODULE=etc

# Source files
MODULE_SRC=readcfg.cpp

# Actually include the makefile
include ../makefile
